import './style.css';
import { rollTrait, activate, damage } from './lore.js';
const $ = s => document.querySelector(s);
$('#app').innerHTML = `
<header><div class="brand">friend<b>smash</b> ✳</div><span class="pill">FRIENDS IN. CHAOS OUT.</span></header>
<main><div class="intro"><div><div class="eyebrow">THE FRIENDSHIP TEST · ARENA 01</div><h1>오늘도 친구는 전설이 된다.</h1><p>얼굴은 친구인데, 능력은 왜 이래? 구경하고, 개입하고, 같이 웃어요.</p></div><button id="start" class="primary">경기 시작 ↗</button></div>
<div class="layout"><section><div class="arena"><div class="arena-head"><span class="live">● <span id="status">READY TO SMASH</span></span><span id="timer">00:00 / 01:00</span></div><div class="stage"><canvas id="arena" aria-label="친구들이 충돌하는 물리 아레나"></canvas><div class="overlay" id="overlay"><span class="eyebrow">LET THE LORE BEGIN</span><h2>누가 제일 웃길까?</h2><p>친구를 추가하거나 바로 시작하세요.</p></div></div><div class="controls"><button data-action="wind">💨 돌풍</button><button data-action="heal">🍪 모두에게 간식</button><button data-action="chaos">⚡ 대혼란</button></div></div><p class="hint">관전만 해도 좋아요. 개입은 5초에 한 번 · 매 경기 새로운 친구 전설</p></section>
<aside><div class="panel"><h2>참가자 <span id="count"></span></h2><p>2–6명 · 이름 아래 능력을 확인하세요.</p><div id="roster"></div><form id="add"><input id="name" placeholder="친구 이름" maxlength="16" required aria-label="친구 이름"><label class="upload">친구 얼굴 (선택)<input id="photo" type="file" accept="image/*"></label><button id="add-button">+ 친구 입장</button></form><p id="photo-status" role="status">사진은 이 브라우저 안에서만 처리돼요.</p></div><div class="panel feed"><h2>📣 오늘의 친구 전설</h2><div id="events" aria-live="polite"><p>승패보다 오래 남을 흑역사, 곧 시작됩니다.</p></div></div></aside></div><div class="footer"><span>LOCAL FACES. LEGENDARY FRIENDS.</span><span>사진 업로드 없음 · 아레나 MVP</span></div></main>
<dialog id="crop-dialog"><h2>친구 얼굴 맞추기</h2><p id="crop-message"></p><canvas id="crop" width="360" height="360"></canvas><p>사진을 드래그해서 얼굴을 원 안에 맞추세요.</p><label>확대<input id="zoom" type="range" min="1" max="4" step="0.01" value="1"></label><div class="actions"><button id="save-crop" class="primary">이 얼굴로 입장</button><button id="cancel-crop">취소</button></div></dialog>`;
const colors = ['#d5ff63','#b6a1ff','#ff987f','#7bdbe6','#ffce69','#ed99d9'];
let roster = ['민수','지우','수빈','준호'].map((name,i)=>({name,emoji:['😎','😈','🥸','🥹'][i],trait:rollTrait(),color:colors[i]}));
let fighters=[],running=false,elapsed=0,last=0,cooldown=0,match=0,pendingFace=null,events=[];
const canvas=$('#arena'),ctx=canvas.getContext('2d'), W=900,H=600;
canvas.width=W;canvas.height=H;
function renderRoster(){
 $('#count').textContent=`(${roster.length}/6)`; $('#roster').replaceChildren();
 roster.forEach((f,i)=>{const row=document.createElement('div');row.className='fighter';const avatar=document.createElement(f.face?'img':'span');avatar.className='avatar';if(f.face){avatar.src=f.face.src;avatar.alt=f.name;}else avatar.textContent=f.emoji;const info=document.createElement('div');const name=document.createElement('strong');name.textContent=f.name;const trait=document.createElement('div');trait.className='trait';trait.textContent=f.trait.name;trait.title=f.trait.description;const bar=document.createElement('div');bar.className='bar';const fill=document.createElement('i');fill.style.width=`${fighters[i]?.hp??100}%`;bar.append(fill);info.append(name,trait,bar);const remove=document.createElement('button');remove.className='remove';remove.textContent='×';remove.setAttribute('aria-label',`${f.name} 제외`);remove.disabled=running||roster.length<=2;remove.onclick=()=>{roster.splice(i,1);fighters=[];renderRoster();};row.append(avatar,info,remove);$('#roster').append(row);});
 $('#add-button').disabled=running||roster.length>=6;$('#start').disabled=roster.length<2;
}
function log(message){events.unshift(message);events=events.slice(0,5);$('#events').replaceChildren(...events.map(t=>{const el=document.createElement('div');el.className='event';el.textContent=t;return el;}));}
function proc(f){f.procs++;f.toast=f.trait.toast;f.toastUntil=elapsed+2;log(`${f.name} · ${f.trait.toast}`);}
function start(){match++;elapsed=0;cooldown=0;events=[];roster.forEach(f=>f.trait=rollTrait(f.trait.id));fighters=roster.map((f,i)=>({...f,x:W/2+Math.cos(i/roster.length*Math.PI*2)*210,y:H/2+Math.sin(i/roster.length*Math.PI*2)*170,vx:(Math.random()-.5)*300,vy:(Math.random()-.5)*300,hp:100,nextProc:2+i,boostUntil:0,procs:0,revived:false}));running=true;$('#overlay').classList.add('hidden');$('#status').textContent=`ROUND ${String(match).padStart(2,'0')} · LIVE`;$('#start').textContent='리매치 ↻';log('새 능력 배정 완료! 오늘의 전설을 만들어 보세요.');renderRoster();}
$('#start').onclick=start;
function finish(){running=false;const ranked=[...fighters].sort((a,b)=>b.hp-a.hp);const legend=[...fighters].sort((a,b)=>b.procs-a.procs)[0];$('#overlay').classList.remove('hidden');$('#overlay').replaceChildren();const title=document.createElement('h2');title.textContent=`${ranked[0].name}, 끝까지 버텼다!`;const p=document.createElement('p');p.textContent=`오늘의 전설: ${legend.name} · ${legend.trait.name} (${legend.procs}회 발동)`;$('#overlay').append(title,p);$('#status').textContent='LEGEND COMPLETE';log(p.textContent);renderRoster();}
function step(dt){elapsed+=dt;const alive=fighters.filter(f=>f.hp>0);for(const f of alive){if(activate(f,alive,elapsed))proc(f);const speed=Math.hypot(f.vx,f.vy);if(speed<110){f.vx+=Math.cos(elapsed+f.x)*20;f.vy+=Math.sin(elapsed+f.y)*20;}if(speed>430){f.vx*=430/speed;f.vy*=430/speed;}f.x+=f.vx*dt;f.y+=f.vy*dt;for(const [p,v,max] of [['x','vx',W],['y','vy',H]]){if(f[p]<38){f[p]=38;f[v]=Math.abs(f[v]);}if(f[p]>max-38){f[p]=max-38;f[v]=-Math.abs(f[v]);}}}
 for(let i=0;i<alive.length;i++)for(let j=i+1;j<alive.length;j++){const a=alive[i],b=alive[j],dx=b.x-a.x,dy=b.y-a.y,d=Math.hypot(dx,dy);if(d>=72)continue;const nx=d?dx/d:1,ny=d?dy/d:0,overlap=(72-d)/2;a.x-=nx*overlap;a.y-=ny*overlap;b.x+=nx*overlap;b.y+=ny*overlap;const relative=(b.vx-a.vx)*nx+(b.vy-a.vy)*ny;if(relative>=0)continue;a.vx+=relative*nx;a.vy+=relative*ny;b.vx-=relative*nx;b.vy-=relative*ny;for(const [target,attacker] of [[a,b],[b,a]]){if(damage(target,attacker.trait.id==='rage'&&attacker.boostUntil>elapsed?16:8))proc(target);if(attacker.trait.id==='traitor'&&elapsed>=attacker.nextProc){attacker.hp=Math.min(100,attacker.hp+8);attacker.nextProc=elapsed+4;proc(attacker);}}}
 if(elapsed>=60||fighters.filter(f=>f.hp>0).length<=1)finish();
}
function draw(){ctx.clearRect(0,0,W,H);ctx.fillStyle='#191e25';ctx.fillRect(0,0,W,H);ctx.fillStyle='#303640';for(let x=25;x<W;x+=30)for(let y=25;y<H;y+=30){ctx.beginPath();ctx.arc(x,y,1,0,Math.PI*2);ctx.fill();}ctx.strokeStyle='#404936';ctx.lineWidth=2;ctx.beginPath();ctx.ellipse(W/2,H/2,260,220,0,0,Math.PI*2);ctx.stroke();ctx.fillStyle='#ffffff07';ctx.font='900 75px sans-serif';ctx.textAlign='center';ctx.fillText('FRIENDSMASH',W/2,H/2+25);
 const visible=fighters.length?fighters:roster.map((f,i)=>({...f,x:W/2+Math.cos(i/roster.length*Math.PI*2)*210,y:H/2+Math.sin(i/roster.length*Math.PI*2)*170,hp:100}));
 for(const f of visible){ctx.save();ctx.translate(f.x,f.y);ctx.globalAlpha=f.hp>0?1:.22;ctx.strokeStyle=f.color;ctx.fillStyle=f.color;ctx.lineWidth=8;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(0,20);ctx.lineTo(0,47);ctx.moveTo(-18,34);ctx.lineTo(18,34);ctx.moveTo(0,47);ctx.lineTo(-14,60);ctx.moveTo(0,47);ctx.lineTo(14,60);ctx.stroke();ctx.beginPath();ctx.arc(0,0,30,0,Math.PI*2);ctx.fill();if(f.face){ctx.save();ctx.clip();ctx.drawImage(f.face,-30,-30,60,60);ctx.restore();}else{ctx.font='36px sans-serif';ctx.fillText(f.emoji,0,13);}ctx.fillStyle='#fff';ctx.font='bold 15px sans-serif';ctx.fillText(f.name,0,-47);ctx.fillStyle=f.color;ctx.font='12px sans-serif';ctx.fillText(f.trait.name,0,-31);if(f.toastUntil>elapsed){ctx.fillStyle='#fff';ctx.font='bold 15px sans-serif';ctx.fillText(f.toast,0,-72);}ctx.restore();}}
let ui=0;function frame(now){const dt=Math.min((now-last)/1000,.035);last=now;if(running)step(dt);draw();if(now-ui>200){ui=now;$('#timer').textContent=`00:${String(Math.min(60,Math.floor(elapsed))).padStart(2,'0')} / 01:00`;document.querySelectorAll('[data-action]').forEach(b=>b.disabled=!running||elapsed<cooldown);if(running)renderRoster();}requestAnimationFrame(frame);}requestAnimationFrame(frame);renderRoster();
for(const button of document.querySelectorAll('[data-action]'))button.onclick=()=>{if(!running||elapsed<cooldown)return;cooldown=elapsed+5;for(const f of fighters.filter(f=>f.hp>0)){if(button.dataset.action==='heal')f.hp=Math.min(100,f.hp+12);else if(button.dataset.action==='wind')f.vx+=230;else{const angle=Math.random()*Math.PI*2;f.vx=Math.cos(angle)*400;f.vy=Math.sin(angle)*400;}}log(`관전자 개입 · ${button.textContent}`);};
$('#add').onsubmit=e=>{e.preventDefault();if(running||roster.length>=6)return;const name=$('#name').value.trim();if(!name)return;roster.push({name,emoji:'🤩',face:pendingFace,color:colors.find(c=>!roster.some(f=>f.color===c))||colors[0],trait:rollTrait()});pendingFace=null;$('#add').reset();$('#photo-status').textContent='사진은 이 브라우저 안에서만 처리돼요.';fighters=[];renderRoster();};
// FaceDetector never sends image pixels to a server. Unsupported browsers use the same local crop editor.
let source,scale=1,base=1,offset={x:0,y:0},drag;
const crop=$('#crop'),cc=crop.getContext('2d');
function paintCrop(){cc.clearRect(0,0,360,360);cc.fillStyle='#101318';cc.fillRect(0,0,360,360);const s=base*scale;cc.drawImage(source,offset.x,offset.y,source.width*s,source.height*s);cc.fillStyle='#0009';cc.beginPath();cc.rect(0,0,360,360);cc.arc(180,180,140,0,Math.PI*2,true);cc.fill('evenodd');cc.strokeStyle='#d5ff63';cc.lineWidth=2;cc.beginPath();cc.arc(180,180,140,0,Math.PI*2);cc.stroke();}
$('#photo').onchange=async e=>{const file=e.target.files[0];if(!file)return;pendingFace=null;$('#add-button').disabled=true;$('#photo-status').textContent='얼굴 확인 중…';const url=URL.createObjectURL(file);try{source=new Image();source.src=url;await source.decode();base=Math.max(360/source.width,360/source.height);scale=1;offset={x:(360-source.width*base)/2,y:(360-source.height*base)/2};let detected=false;if('FaceDetector' in window){try{const faces=await new window.FaceDetector({fastMode:true,maxDetectedFaces:1}).detect(source);if(faces.length){const b=faces[0].boundingBox;base=280/(Math.max(b.width,b.height)*1.35);offset={x:180-(b.x+b.width/2)*base,y:180-(b.y+b.height/2)*base};detected=true;}}catch{}}
 $('#crop-message').textContent=detected?'얼굴을 찾았어요! 위치를 확인하고 조절하세요.':'자동 감지를 사용할 수 없어요. 직접 얼굴을 맞춰주세요.';$('#zoom').value=1;paintCrop();$('#crop-dialog').showModal();}catch{$('#photo-status').textContent='사진을 열 수 없어요. 다른 이미지로 다시 시도하세요.';}finally{URL.revokeObjectURL(url);renderRoster();}};
crop.onpointerdown=e=>{drag={x:e.clientX,y:e.clientY};crop.setPointerCapture(e.pointerId);};crop.onpointermove=e=>{if(!drag)return;const ratio=360/crop.getBoundingClientRect().width;offset.x+=(e.clientX-drag.x)*ratio;offset.y+=(e.clientY-drag.y)*ratio;drag={x:e.clientX,y:e.clientY};paintCrop();};crop.onpointerup=crop.onpointercancel=()=>drag=null;
$('#zoom').oninput=e=>{const next=Number(e.target.value);offset.x=180+(offset.x-180)*next/scale;offset.y=180+(offset.y-180)*next/scale;scale=next;paintCrop();};
$('#save-crop').onclick=async()=>{const out=document.createElement('canvas');out.width=out.height=280;const c=out.getContext('2d');c.beginPath();c.arc(140,140,140,0,Math.PI*2);c.clip();c.drawImage(source,offset.x-40,offset.y-40,source.width*base*scale,source.height*base*scale);pendingFace=new Image();pendingFace.src=out.toDataURL('image/png');await pendingFace.decode();$('#photo-status').textContent='얼굴 준비 완료 · 친구 입장을 눌러주세요.';$('#crop-dialog').close();};
$('#cancel-crop').onclick=()=>$('#crop-dialog').close();$('#crop-dialog').onclose=()=>{if(!pendingFace){$('#photo').value='';$('#photo-status').textContent='사진 선택 취소 · 이름만으로도 입장할 수 있어요.';}};
